name: aierp

services:
  ollama-telegram-bot:
    container_name: ollamatelegrambot   # Sets the custom container name
    image: ollama-telegram-bot:1.0.0    # Names and tags the built image with a version
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - aicp_net

networks:
  aicp_net:
    external: true